# Generated by Django 3.1 on 2020-09-07 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200908_0112'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Offer1',
            new_name='Offer',
        ),
    ]
